#![deny(clippy::all)]

pub mod adapters;
pub mod ansi_keys;
mod config;
pub mod domain;
mod error;
pub mod handlers;
mod lock_helpers;
mod metrics;
mod pty_session;
mod repository;
mod select_helpers;
mod server;
mod session;
mod terminal_state;
pub mod transport;
mod usecase_container;
pub mod usecases;
mod wait;

pub use config::DaemonConfig;
pub use error::DaemonError;
pub use error::DomainError;
pub use error::SessionError;
pub use lock_helpers::LOCK_TIMEOUT;
pub use lock_helpers::MAX_BACKOFF;
pub use lock_helpers::acquire_session_lock;
pub use metrics::DaemonMetrics;
pub use pty_session::PtySession;
pub use repository::SessionRepository;
pub use repository::SessionSnapshot;
pub use select_helpers::navigate_to_option;
pub use select_helpers::parse_select_options;
pub use select_helpers::strip_ansi_codes;
pub use server::start_daemon;
pub use session::ErrorEntry;
pub use session::PersistedSession;
pub use session::RecordingFrame;
pub use session::RecordingStatus;
pub use session::Session;
pub use session::SessionId;
pub use session::SessionInfo;
pub use session::SessionManager;
pub use session::SessionPersistence;
pub use session::TraceEntry;
pub use terminal_state::TerminalState;
pub use usecase_container::ElementUseCases;
pub use usecase_container::InputUseCases;
pub use usecase_container::SessionUseCases;
pub use usecase_container::UseCaseContainer;
pub use wait::StableTracker;
pub use wait::WaitCondition;
pub use wait::check_condition;

pub use transport::TransportConnection;
pub use transport::TransportError;
pub use transport::TransportListener;
pub use transport::unix_socket::UnixSocketConnection;
pub use transport::unix_socket::UnixSocketListener;

pub type Result<T> = std::result::Result<T, SessionError>;
