#![deny(clippy::all)]
mod config;
mod error;
mod file_lock;
pub mod handlers;
mod live_preview;
mod lock_helpers;
mod metrics;
mod pty_session;
mod repository;
mod router;
mod server;
mod session;
mod signal_handler;
mod sleeper;
mod terminal_state;
#[cfg(test)]
pub mod test_support;
pub mod transport;
mod usecase_container;

pub use crate::usecases::ports::{LivePreviewError, SessionError};
pub use config::DaemonConfig;
pub use error::DaemonError;
pub use error::DomainError;
pub use file_lock::LockFile;
pub use file_lock::remove_lock_file;
pub use live_preview::LivePreviewManager;
pub use lock_helpers::LOCK_TIMEOUT;
pub use lock_helpers::MAX_BACKOFF;
pub use lock_helpers::acquire_session_lock;
pub use metrics::DaemonMetrics;
pub use pty_session::PtySession;
pub use repository::SessionSnapshot;
pub use router::Router;
pub use server::start_daemon;
pub use session::DEFAULT_MAX_SESSIONS;
pub use session::ErrorEntry;
pub use session::PersistedSession;
pub use session::RecordingFrame;
pub use session::RecordingStatus;
pub use session::Session;
pub use session::SessionId;
pub use session::SessionInfo;
pub use session::SessionManager;
pub use session::SessionPersistence;
pub use session::TraceEntry;
pub use sleeper::RealSleeper;
pub use terminal_state::TerminalState;
pub use usecase_container::ElementUseCases;
pub use usecase_container::InputUseCases;
pub use usecase_container::SessionUseCases;
pub use usecase_container::UseCaseContainer;

pub use transport::TransportConnection;
pub use transport::TransportError;
pub use transport::TransportListener;
pub use transport::unix_socket::UnixSocketConnection;
pub use transport::unix_socket::UnixSocketListener;

pub type Result<T> = std::result::Result<T, SessionError>;
